apiVersion: v1
data:
  service.slack: |
    token: $slack-token

  template.rollout-canary-started: |
    message: |
      🚀 Canary rollout started for {{.rollout.metadata.name}} in namespace {{.rollout.metadata.namespace}}
      New revision: {{.rollout.status.currentPodHash}}
      Canary weight: {{.rollout.status.canary.weights.canary}}%
    slack:
      attachments: |
        [{
          "title": "🚀 Canary Rollout Started",
          "color": "#18be52",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "New Revision",
              "value": "{{.rollout.status.currentPodHash}}",
              "short": true
            },
            {
              "title": "Canary Weight",
              "value": "{{.rollout.status.canary.weights.canary}}%",
              "short": true
            }
          ]
        }]

  template.rollout-promoted: |
    message: |
      ✅ Rollout {{.rollout.metadata.name}} fully promoted to stable!
      All canary steps completed successfully.
      New revision: {{.rollout.status.currentPodHash}}
    slack:
      attachments: |
        [{
          "title": "✅ Canary Promoted to Stable",
          "color": "good",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "New Revision",
              "value": "{{.rollout.status.currentPodHash}}",
              "short": true
            },
            {
              "title": "Image",
              "value": "{{(index .rollout.spec.template.spec.containers 0).image}}",
              "short": false
            }
          ]
        }]

  trigger.on-rollout-canary-started: |
    - when: rollout.status.phase in ['Progressing'] and rollout.status.currentStepIndex == 0
      oncePer: rollout.metadata.generation
      send: [rollout-canary-started]

  trigger.on-rollout-promoted: |
    - when: rollout.status.phase == 'Healthy' and rollout.status.stableRS == rollout.status.currentPodHash
      oncePer: rollout.metadata.generation
      send: [rollout-promoted]

kind: ConfigMap
metadata:
  annotations:
    freelens.app/resource-version: v1
    meta.helm.sh/release-name: argo-rollouts
    meta.helm.sh/release-namespace: argo-rollouts
  creationTimestamp: "2025-09-23T12:25:28Z"
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/version: v1.8.3
    helm.sh/chart: argo-rollouts-2.40.4
  name: argo-rollouts-notification-configmap
  namespace: argo-rollouts
  resourceVersion: "1954511"
  selfLink: >-
    /api/v1/namespaces/argo-rollouts/configmaps/argo-rollouts-notification-configmap
  uid: 1e005516-d573-496c-b6d8-7318f3910653
