apiVersion: v1
data:
  service.slack: |
    token: $slack-token

  template.rollout-canary-started: |
    message: |
      🚀 Canary rollout started for {{.rollout.metadata.name}} in namespace {{.rollout.metadata.namespace}}
      New revision: {{.rollout.status.currentPodHash}}
      Canary weight: {{.rollout.status.canary.weights.canary}}%
    slack:
      attachments: |
        [{
          "title": "🚀 Canary Rollout Started",
          "color": "#18be52",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "New Revision",
              "value": "{{.rollout.status.currentPodHash}}",
              "short": true
            },
            {
              "title": "Canary Weight",
              "value": "{{.rollout.status.canary.weights.canary}}%",
              "short": true
            }
          ]
        }]

  template.rollout-updated: |
    message: |
      Rollout {{.rollout.metadata.name}} has been updated.
      Revision: {{.rollout.status.currentPodHash}}
      Status: {{.rollout.status.phase}}
    slack:
      attachments: |
        [{
          "title": "Rollout Update",
          "color": "#18be52",
          "fields": [
            {
              "title": "Rollout Name",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "Status",
              "value": "{{.rollout.status.phase}}",
              "short": true
            },
            {
              "title": "Replicas",
              "value": "{{.rollout.status.replicas}}",
              "short": true
            }
          ]
        }]

  template.rollout-completed: |
    message: |
      ✅ Rollout {{.rollout.metadata.name}} completed successfully!
      All replicas are healthy and running.
    slack:
      attachments: |
        [{
          "title": "✅ Rollout Completed",
          "color": "good",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "Image",
              "value": "{{(index .rollout.spec.template.spec.containers 0).image}}",
              "short": false
            }
          ]
        }]

  template.rollout-paused: |
    message: |
      ⏸️ Rollout {{.rollout.metadata.name}} is paused and waiting for promotion.
    slack:
      attachments: |
        [{
          "title": "⏸️ Rollout Paused",
          "color": "warning",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Current Step",
              "value": "{{.rollout.status.currentStepIndex}}",
              "short": true
            },
            {
              "title": "Action Required",
              "value": "Manual promotion needed",
              "short": false
            }
          ]
        }]

  template.rollout-aborted: |
    message: |
      ❌ Rollout {{.rollout.metadata.name}} has been aborted!
    slack:
      attachments: |
        [{
          "title": "❌ Rollout Aborted",
          "color": "danger",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Namespace",
              "value": "{{.rollout.metadata.namespace}}",
              "short": true
            },
            {
              "title": "Reason",
              "value": "{{.rollout.status.message}}",
              "short": false
            }
          ]
        }]

  template.rollout-step-completed: |
    message: |
      Step {{.rollout.status.currentStepIndex}} completed for rollout {{.rollout.metadata.name}}
    slack:
      attachments: |
        [{
          "title": "Step Completed",
          "color": "#18be52",
          "fields": [
            {
              "title": "Rollout",
              "value": "{{.rollout.metadata.name}}",
              "short": true
            },
            {
              "title": "Step",
              "value": "{{.rollout.status.currentStepIndex}}",
              "short": true
            }
          ]
        }]
  trigger.on-rollout-canary-started: |
    - oncePer: rollout.status.canary.currentStepIndex
      when: rollout.status.phase == 'Progressing'
      send: [rollout-canary-started]

  trigger.on-rollout-updated: |
    - when: rollout.status.phase == 'Progressing'
      send: [rollout-updated]

  trigger.on-rollout-completed: |
    - when: rollout.status.phase == 'Healthy'
      send: [rollout-completed]

  trigger.on-rollout-paused: |
    - when: rollout.status.pauseConditions != nil
      send: [rollout-paused]

  trigger.on-rollout-aborted: |
    - when: rollout.status.phase == 'Degraded' || rollout.status.abort == true
      send: [rollout-aborted]

  trigger.on-rollout-step-completed: |
    - when: rollout.status.currentStepIndex != nil
      send: [rollout-step-completed]

kind: ConfigMap
metadata:
  annotations:
    freelens.app/resource-version: v1
    meta.helm.sh/release-name: argo-rollouts
    meta.helm.sh/release-namespace: argo-rollouts
  creationTimestamp: "2025-09-23T12:25:28Z"
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/version: v1.8.3
    helm.sh/chart: argo-rollouts-2.40.4
  name: argo-rollouts-notification-configmap
  namespace: argo-rollouts
  resourceVersion: "1954511"
  selfLink: >-
    /api/v1/namespaces/argo-rollouts/configmaps/argo-rollouts-notification-configmap
  uid: 1e005516-d573-496c-b6d8-7318f3910653
