apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-canary
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-canary-started.slack: argocd
    notifications.argoproj.io/subscribe.on-rollout-promoted.slack: argocd
    notifications.argoproj.io/subscribe.on-rollout-degraded.slack: argocd
    notifications.argoproj.io/subscribe.on-rollout-degraded-analysis.slack: argocd
spec:
  replicas: 4
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-green-canary
  strategy:
    canary:
      stableService: blue-green-canary-active
      canaryService: blue-green-canary-preview
      maxSurge: "25%"
      maxUnavailable: 0
      abortScaleDownDelaySeconds: 300
      analysis:
        templates:
          - templateName: blue-green-canary
        args:
          - name: url
            value: http://blue-green-canary-preview.default.svc.cluster.local:80
      steps:
        - setWeight: 5
        - pause: { duration: 1m }
        - setWeight: 10
        - pause: { duration: 11m }