apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-canary
spec:
  replicas: 4
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-green-canary
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: '50%'
      maxUnavailable: 0
      steps:
        - setWeight: 50
        - pause:
            duration: 1h # 1 hour
        - setWeight: 50
        - pause: {} # pause indefinitely