apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-canary
spec:
  replicas: 4
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-green-canary
  strategy:
    canary:
      analysis:
        templates:
        - templateName: blue-green-canaryblue-green-canary
          args:
          - name: function_id
            value: "5a06fa01-b01b-4292-8b27-acd29d7b1e2c"
      maxSurge: "25%"
      maxUnavailable: 0
      abortScaleDownDelaySeconds: 300
      steps:
        - setWeight: 5
        - pause: { duration: 10m }
        - setWeight: 10
        - pause: { duration: 10m }
        - setWeight: 25
        - pause: { duration: 15m }
        - setWeight: 50
        - pause: { duration: 20m }