apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blue-green-canary-monitor
  labels:
    release: prometheus  # Must match Prometheus Operator’s selector
spec:
  selector:
    matchLabels:
      app: blue-green-canary
  namespaceSelector:
    matchNames:
      - default  # Namespace where the Service is
  endpoints:
    - port: http
      path: /metrics
      interval: 15s